version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: chatbot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: ChatbotDB
      TZ: Asia/Taipei
    ports: ['3306:3306']
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/chatbot_init.sql:/docker-entrypoint-initdb.d/1_init.sql

  services:
  backend:
    build: ./backend
    container_name: chatbot-backend
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpw
      DB_NAME: ChatbotDB
      PORT: 3000
      OLLAMA_URL: http://host.docker.internal:11434/api/generate
    ports:
      - "3001:3000"
    depends_on:
      - mysql


  frontend:
    build: ./chatbot-frontend
    container_name: chatbot-frontend
    ports: ['5173:80']
    depends_on: [backend]

volumes:
  mysql_data:
