# docker-compose.yml
version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: chatbot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: ChatbotDB
      TZ: Asia/Taipei
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/chatbot_init.sql:/docker-entrypoint-initdb.d/1_init.sql
    healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-prootpw"]
    interval: 10s
    timeout: 5s
    retries: 5

  backend:
    build: ./backend
    container_name: chatbot-backend
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpw
      DB_NAME: ChatbotDB
      OLLAMA_URL: http://host.docker.internal:11434/api/generate
    ports:
      - "3001:3000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
